# Copyright (c) 2020 Authors:
#   - Félix Martí Valverde <martivalverde@hotmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

k: 1 # Thrust Propellers
b: 1 # Torque Propellers

# Aerodynamic Friction Matrix
kd:
    xx: 1
    yy: 1
    zz: 1

# Inertial Matrix
inertial:
    xx: 1
    xy: 0
    xz: 0  
    yy: 1
    yz: 0
    zz: 1

gravity: 9.81 # Graviti Force       [m/s^2]
mass: 10 # Mass Vehicle             [kg]

lf: 1.53 # Distance COG-Front       [m]
lr: 1.53 # Distance COG-Rear        [m]
s: 1.53 # Distance COG-Side         [m]